### ISSUE TITLE
Can’t Load Label With Space

### ISSUE THREAD

**Issue by rdp77** [dte-project/blogger#3]
Example of using url labels with spaces https://www.backupotak.com/search/label/Command%20Line%20Interface, in this case it can't be parsed, so it can't load the sitemap

[Reference](https://www.backupotak.com/p/sitemap.html) | [File](https://github.com/dte-project/blogger/blob/master/tabbed-toc.js)

**Comment by taufik-nurrohman** [comment]
Updated. Try again for some time or clear your cache.
